spring:
  application:
    name: Leave-Management
  flyway:
    enabled: true
    baseline-on-migrate: true

  config:
    import: optional:file:.env[.properties]
    
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

  profiles:
    active: dev